Traceback (most recent call last):
  File "C:\Users\Spher\OneDrive\Desktop\CS\AI\Image_Caption\image-captioning\main.py", line 38, in <module>
    checkpoint = torch.load(args.output_dir, map_location=device_type)
  File "C:\Users\Spher\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Spher\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Spher\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: '../out'
Traceback (most recent call last):
  File "C:\Users\Spher\OneDrive\Desktop\CS\AI\Image_Caption\image-captioning\main.py", line 38, in <module>
    checkpoint = torch.load(args.output_dir, map_location=device_type)
  File "C:\Users\Spher\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Spher\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Spher\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: '../out'